image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  SE_OPTS: "--no-sandbox"

cache:
  paths:
    - .pip-cache/

stages:
  - test
  - security

before_script:
  - python -V
  - pip install -r requirements.txt

test_selenium:
  stage: test
  services:
    - selenium/standalone-chrome:latest
  script:
    - pytest tests/test_carrito.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 1 week

# Configuración de SAST (Security Analysis)
sast:
  stage: security
  include:
    - template: Security/SAST.gitlab-ci.yml
